package gson.to.java;

import gson.to.java.model.JsonRootBean;
import net.sf.json.JSONObject;

public class GsonToJava {
	
	/**
	 * 一个json转javaBean的例子，其中需要注意的点，json串中的属性名，首字母不能是大写，
	 *  例如 queryFlightRevenueRS 可以取到， QueryFlightRevenueRS则不可以，除了首字母 其他的字母无大写小要求，
	 * @JsonProperty("Queryflightrevenuers") 关于这注解，不知有何用
	 * @param args
	 */
	public static void main(String[] args) {
		
		System.out.println(JSONObject.toBean(JSONObject.fromObject("{\"StrD\":\"1111\"}")));
		
		// 根据以下这些内容，发现json串中的属性名对应在set方法名上 qwer 对应 setQwer(){}
		JsonRootBean strRt = (JsonRootBean) JSONObject.toBean(JSONObject.fromObject("{\"qwer\":\"qwe111asdfzxcv\"}"), JsonRootBean.class);
		System.out.println(strRt.getQwre());
		
		JSONObject jsonObject = JSONObject.fromObject(json);
		
		JsonRootBean root = (JsonRootBean) JSONObject.toBean(jsonObject, JsonRootBean.class);
		System.out.println(root.getQueryflightrevenuers().getResponse().getFveResult().getFlightInfoDt());
		System.out.println(root);
	}
	
	private static String json = "{" + 
			"  \"Queryflightrevenuers\": {" + 
			"    \"response\": {" + 
			"      \"fveResult\": {" + 
			"        \"flightInfoDt\": [" + 
			"          {" + 
			"            \"dptDt\":\"20200509\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200509\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"750.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"3\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"1500.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"3\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"1500.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"3\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"3000.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"3\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"3000.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"6\"," + 
			"                    \"ttlRev\":\"4500.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200510\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200510\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"1\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"1\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"1\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200511\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200511\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"1\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"2\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"3\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"3\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200512\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200512\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"0\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200515\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200515\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"1\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"1\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"1\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200522\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200522\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"0\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }," + 
			"          {" + 
			"            \"dptDt\":\"20200528\"," + 
			"            \"flightInfo\":[" + 
			"              {" + 
			"                \"cbnSeq\":\"FAC/P/YTHMGSLQEVRKINDOBXUWJZ/\"," + 
			"                \"dptArvAirpt\":\"CTUBHY\"," + 
			"                \"fltDptDt\":\"20200528\"," + 
			"                \"fltNbr\":\"EU2715\"," + 
			"                \"fltOffc\":\"UEA001\"," + 
			"                \"fltSubOffc\":\"\"," + 
			"                \"segInfo\":[" + 
			"                  {" + 
			"                    \"avgDisc\":\"0.00\"," + 
			"                    \"avgPrice\":\"0.00\"," + 
			"                    \"fltEqt\":\"319\"," + 
			"                    \"segCtyPair\":\"CTUBHY\"," + 
			"                    \"segDptTm\":\"0555\"," + 
			"                    \"supClazz\":[" + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"F\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"A\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"C\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"F\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"P\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"P\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }," + 
			"                      {" + 
			"                        \"subClazz\":[" + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Y\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"T\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"H\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"M\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"G\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"S\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"L\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Q\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"E\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"V\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"R\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"K\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"I\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"N\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"D\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"O\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"B\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"X\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"U\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"W\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"J\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }," + 
			"                          {" + 
			"                            \"subBkd\":\"0\"," + 
			"                            \"subCbn\":\"Z\"," + 
			"                            \"subGrs\":\"0\"," + 
			"                            \"subGrt\":\"0\"," + 
			"                            \"subVto\":\"0.0\"" + 
			"                          }" + 
			"                        ]," + 
			"                        \"supBkd\":\"0\"," + 
			"                        \"supCbn\":\"Y\"," + 
			"                        \"supRev\":\"0.0\"" + 
			"                      }" + 
			"                    ]," + 
			"                    \"ttlBkd\":\"0\"," + 
			"                    \"ttlRev\":\"0.0\"" + 
			"                  }" + 
			"                ]" + 
			"              }" + 
			"            ]" + 
			"          }" + 
			"        ]," + 
			"        \"qryDt\": \"20200825\"," + 
			"        \"fltNbr\": \"EU2715\"," + 
			"        \"agtNbr\": \"pek099\"," + 
			"        \"usrOffc\": \"sha001\"," + 
			"        \"qryTm\": \"1454\"" + 
			"      }" + 
			"    }," + 
			"    \"sessionID\": \"session\"," + 
			"    \"version\": \"1.0\"," + 
			"    \"requestID\": \"REQ42574273709253267396\"," + 
			"    \"success\": \"1\"," + 
			"    \"transactionID\": \"TRA22086491435061632673\"" + 
			"  }" + 
			"}";

}
